alpha: 1.0
benchmark: false
beta: 1.0
cls_batch_num: 6
cls_image_shape: 3, 48, 192
cls_model_dir: null
cls_thresh: 0.9
cpu_threads: 10
crop_res_save_dir: ./output
det_algorithm: DB
det_box_type: quad
det_db_box_thresh: 0.6
det_db_score_mode: fast
det_db_thresh: 0.3
det_db_unclip_ratio: 1.5
det_east_cover_thresh: 0.1
det_east_nms_thresh: 0.2
det_east_score_thresh: 0.8
det_limit_side_len: 960
det_limit_type: max
det_model_dir: null
det_pse_box_thresh: 0.85
det_pse_min_area: 16
det_pse_scale: 1
det_pse_thresh: 0
det_sast_nms_thresh: 0.2
det_sast_score_thresh: 0.5
draw_img_save_dir: ./inference_results
drop_score: 0.5
e2e_algorithm: PGNet
e2e_char_dict_path: ./ppocr/utils/ic15_dict.txt
e2e_limit_side_len: 768
e2e_limit_type: max
e2e_model_dir: null
e2e_pgnet_mode: fast
e2e_pgnet_score_thresh: 0.5
e2e_pgnet_valid_set: totaltext
enable_mkldnn: false
fourier_degree: 5
gpu_mem: 500
image_dir: null
ir_optim: true
label_list:
- '0'
- '180'
max_batch_size: 10
max_text_length: 25
min_subgraph_size: 15
page_num: 0
precision: fp32
process_id: 0
rec_algorithm: SVTR_LCNet
rec_batch_num: 6
rec_char_dict_path: ./ppocr/utils/ppocr_keys_v1.txt
rec_image_inverse: true
rec_image_shape: 3, 48, 320
rec_model_dir: null
save_crop_res: false
save_log_path: ./log_output/
scales:
- 8
- 16
- 32
show_log: true
sr_batch_num: 1
sr_image_shape: 3, 32, 128
sr_model_dir: null
total_process_num: 1
use_angle_cls: false
use_dilation: false
use_gpu: true
use_mp: false
use_npu: false
use_onnx: false
use_pdserving: false
use_space_char: true
use_tensorrt: false
use_xpu: false
vis_font_path: ./doc/fonts/simfang.ttf
warmup: false
